### ISSUE TITLE
Design logo

### ISSUE THREAD

**Issue by garrows** [campjs/campjs-ix#3]
Every year CampJS has had a new logo made up for the website, swag and stickers.

**Comment by gupta-kartik** [comment]
The logo will be present on all communication from CampJS, brochures, banners, website and even email signatures. If you are interested in submitting a logo, get in touch at organisers@campjs.com

**Comment by AshKyd** [comment]
We've had some awesome peeps submit art in the past, but considering the effort involved each camp we should consider whether there's budget and/or appetite to pay someone professionally.

There's been talk of iterating rather than rebranding for every camp, so that might make this a better investment. Food for thought.

**Comment by gupta-kartik** [comment]
![campjs-logo](https://user-images.githubusercontent.com/4622084/36971593-0b261038-20b8-11e8-82e6-607c1fdb7f8e.jpg)

Thanks to alan.y.myers@gmail.com for the logo!
