### ISSUE TITLE
Attendee preferences

### ISSUE THREAD

**Issue by AshKyd** [campjs/campjs-ix#38]
# What do we need to know from attendees?

1. Food preference/allergies
1. Accommodation preference (#37)
1. Photography preference (#17)
1. Bus/transport preference (#20) *
1. Optional: demographic info?

This was implemented into the ti.to ticketing process.

**Comment by garrows** [comment]
This was organised last time using ti.to which has a questionnaire section during signup. 
Photography preference was asked when handing out lanyards.

**Comment by AshKyd** [comment]
Cool. Let's also do photography preference at ticketing time so we know more accurately how many lanyards we need.

**Comment by mcne65** [comment]
I think people should be aware that @garrows there will be photography being taken on those days, so how about just writing that down on sheet? No, demographics should be changed to any accessibility needs so that we can accommodate for those with disabilities and how we can support them. There should also be something for people who are bringing their cars or not and whether they can offer a drop off afterwards camp

**Comment by AshKyd** [comment]
This is a diversity and inclusiveness feature we're adopting from many other conferences. If you'd like more info as to why we're doing this, check out this [ada initiative post](https://adainitiative.org/2013/07/04/another-way-to-attract-women-to-conferences-photography-policies/).

**Comment by AshKyd** [comment]
We had feedback that some folks mightn't have known how to answer the questions at ticketing time, but the ticketing process lets you change these after the fact so it's probably okay.
